### ISSUE TITLE
An error during the git clone step, leaves you in the created vendor branch

### ISSUE THREAD

**Issue by spkane** [websterclay/knife-github-cookbooks#13]
So, if you try to download an invalid cookbook from github, you will still get a  pristine copy branch and then be left in that branch after the error. It would be ideal if the validity of the cookbook was either checked before creating the branch, or the branch was backed out when an error occurs.

$ knife cookbook github install 37s_cookbooks/dhcpd

Installing dhcpd from git://github.com/37s_cookbooks/dhcpd.git to /Users/skane/dev/kavi/git/chef/cookbooks
Checking out the master branch.
Creating pristine copy branch chef-vendor-dhcpd
ERROR: Chef::Exceptions::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git clone git://github.com/37s_cookbooks/dhcpd.git _tmp_chef_dhcpd ----
STDOUT: Cloning into _tmp_chef_dhcpd...
STDERR: fatal: remote error: 
  Could not find Repository 37s_cookbooks/dhcpd
---- End output of git clone git://github.com/37s_cookbooks/dhcpd.git _tmp_chef_dhcpd ----
Ran git clone git://github.com/37s_cookbooks/dhcpd.git _tmp_chef_dhcpd returned 128

$ git status
# On branch chef-vendor-dhcpd

nothing to commit (working directory clean)

**Comment by samumbach** [comment]
This also affects `knife cookbook site install`, so this may be a Chef bug.

**Comment by markba** [comment]
Same issue.

**Comment by checchia** [comment]
Same issue. not affect "site install" only "github install"
