### ISSUE TITLE
If not in master branch, commit is still made in master

### ISSUE THREAD

**Issue by skalnik** [websterclay/knife-github-cookbooks#5]
If you're working on a branch of your chef-repo and run `knife cookbook github install …` the new commit is placed in master branch. While isn't a show stopper, it is unexpected behavior. Or at least was unexpected by me.

**Comment by jnewland** [comment]
I've experienced this same bug with `knife cookbook site install`.

http://tickets.opscode.com/browse/CHEF-2335

Are you affected by that too?

**Comment by skalnik** [comment]
Yep, I'm experiencing that issue as well. I guess that's the cause of this.

**Comment by jnewland** [comment]
Make some noise on the upstream issue. Closing this for now.
